version: 0.2

phases:
  install:
    commands:
      - yum install -y git ncurses-devel
      - yum groupinstall -y "Development Tools"
  pre_build:
    commands:
      - make git-get
  build:
    commands:
      - make vim
      - make libt
      - make bootstrap
  post_build:
    commands:
      - ls -l release/
      - cat bootstrap
      - aws cloudformation package --template-file template.yml --s3-bucket ${BUCKET} --output-template-file deploy.yml

artifacts:
  type: zip
  files:
    - template.yml
    - deploy.yml
